app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');
Route::get('changepwd', 'UserController@edit');
Route::patch('changepwd/update/{role} ', ['as'=>'user.update','uses'=>'UserController@update']);
Route::post('home/store', ['as'=>'home.store','uses'=>'HomeController@store']);
Route::get('home/getAcademy', ['as'=>'home.getAcademy','uses'=>'HomeController@getAcademy']);
Route::post('upload/uploadFile',['as'=>'upload.uploadfile','uses'=>'UploadController@uploadFile']);
Route::post('upload/uploadImage',['as'=>'upload.uploadimage','uses'=>'UploadController@uploadImage']);
Route::post('upload/deleteFile',['as'=>'upload.deletefile','uses'=>'UploadController@deleteFile']);
Route::get('download/result',function(){
    $file = storage_path('exports/enroll.xls');

    if(file_exists($file)){
        return response()->download($file,date('Y',time()).'届敬文新教育录取名单.xls');
    }
});
Route::get('download/admission',function(){
    $file = storage_path('app/public/firstresult.docx');
    if(file_exists($file)){
        return response()->download($file,'苏州科技大学敬文书院2016级新生拟录取名单公示.docx');
    }
});

Route::get('download/word', ['as'=>'download.word','uses'=>'HomeController@getword']);

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    //Route::auth();
    Route::get('login', 'Auth\AuthController@getLogin');
    Route::post('login', 'Auth\AuthController@postLogin');
    Route::get('logout', 'Auth\AuthController@logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth.admin'], function () {

    Route::get('home', ['as' => 'admin.home', 'uses' => 'HomeController@index']);
    Route::get('/', ['as' => 'admin.home', 'uses' => 'HomeController@index']);
    Route::resource('users', 'UserController');
    Route::post('users/destroyall',['as'=>'admin.users.destroy.all','uses'=>'UserController@destroyAll']);
    Route::resource('role', 'RoleController');
    Route::post('role/destroyall',['as'=>'admin.role.destroy.all','uses'=>'RoleController@destroyAll']);
    Route::get('role/{id}/permissions',['as'=>'admin.role.permissions','uses'=>'RoleController@permissions']);
    Route::post('role/{id}/permissions',['as'=>'admin.role.permissions','uses'=>'RoleController@storePermissions']);
    Route::resource('permission', 'PermissionController');
    Route::post('permission/destroyall',['as'=>'admin.permission.destroy.all','uses'=>'PermissionController@destroyAll']);
    Route::post('upload/uploadFile',['as'=>'admin.upload.uploadfile','uses'=>'UploadController@uploadFile']);
    Route::post('upload/uploadImage',['as'=>'admin.upload.uploadimage','uses'=>'UploadController@uploadImage']);
    Route::post('upload/deleteFile',['as'=>'admin.upload.deletefile','uses'=>'UploadController@deleteFile']);

    Route::resource('registers', 'RegisterController');
    Route::post('registers/destroyall',['as'=>'admin.registers.destroy.all','uses'=>'RegisterController@destroyAll']);
    Route::get('registers/export/{registers}',['as'=>'admin.registers.export','uses'=>'RegisterController@export']);
    Route::get('exportallexcel',['as'=>'admin.registers.getallexcel','uses'=>'RegisterController@getAllExcel']);
    Route::get('exportall',['as'=>'admin.export.all','uses'=>'RegisterController@exportAll']);
    Route::get('download',['as'=>'admin.download','uses'=>'RegisterController@download']);
    Route::post('registers/check',['as'=>'admin.registers.check','uses'=>'RegisterController@check']);
    Route::post('registers/goinit',['as'=>'admin.registers.goinit','uses'=>'RegisterController@goinit']);
    Route::post('registers/complete',['as'=>'admin.register.complete','uses'=>'RegisterController@complete']);
    Route::post('registers/open',['as'=>'admin.register.open','uses'=>'RegisterController@open']);

    Route::get('upload/import',['as'=>'admin.upload','uses'=>'StudentController@upload']);

    Route::resource('students', 'StudentController');
    Route::post('students/import',['as'=>'admin.students.import','uses'=>'StudentController@import']);
    Route::post('students/destroyall',['as'=>'admin.students.destroy.all','uses'=>'StudentController@destroyAll']);
    Route::get('deleteall',['as'=>'admin.students.delete.all','uses'=>'StudentController@deleteAll']);

    Route::resource('systems', 'SystemController');

});



Route::any('captcha', function()
{
    if (Request::getMethod() == 'POST')
    {
        $rules = ['captcha' => 'required|captcha'];
        $validator = Validator::make(Request::all(), $rules);
        if ($validator->fails())
        {
            echo '<p style="color: #ff0000;">Incorrect!</p>';
        }
        else
        {
            echo '<p style="color: #00ff30;">Matched :)</p>';
        }
    }

    $form = '<form method="post" action="captcha">';
    $form .= '<input type="hidden" name="_token" value="' . csrf_token() . '">';
    $form .= '<p>' . captcha_img() . '</p>';
    $form .= '<p><input type="text" name="captcha"></p>';
    $form .= '<p><button type="submit" name="check">Check</button></p>';
    $form .= '</form>';
    return $form;
});

resources/views/admin/_partials/breadcrumbs.blade.php
@if($breadcrumbs)
    <h1>
        {{ $breadcrumbs[1]->title }}中心
        <small></small>
    </h1>
    <ol class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)
            @if (!$breadcrumb->last)
                <li><a href="{{ $breadcrumb->url }}"><i class="fa fa-dashboard"></i>{{ $breadcrumb->title }}</a></li>
            @else
                <li class="active">{{ $breadcrumb->title }}</li>
            @endif
        @endforeach
    </ol>
@endif

resources/views/admin/_partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2015-2016 <a href="http://yearn.cc">Jiyi</a>.</strong> All rights
    reserved.
</footer>

resources/views/admin/_partials/header.blade.php
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>J</b>IYIS</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>敬文书院</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">切换导航</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">你有4条消息</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li><!-- start message -->
                                        <a href="#">
                                            <div class="pull-left">
                                                <img src="/assets/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                            </div>
                                            <h4>
                                                Support Team
                                                <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                            </h4>
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <!-- end message -->
                                </ul>
                            </li>
                            <li class="footer"><a href="#">查看所有消息</a></li>
                        </ul>
                    </li>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">你有10条通知</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="#">查看所有通知</a></li>
                        </ul>
                    </li>
                    <!-- Tasks: style can be found in dropdown.less -->
                    <li class="dropdown tasks-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">你有9个任务</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li><!-- Task item -->
                                        <a href="#">
                                            <h3>
                                                Design some buttons
                                                <small class="pull-right">20%</small>
                                            </h3>
                                            <div class="progress xs">
                                                <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">20% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <!-- end task item -->
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="#">查看所有任务</a>
                            </li>
                        </ul>
                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="/assets/images/user.jpg" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ $curuser->nickname }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="/assets/images/user.jpg" class="img-circle" alt="User Image">

                                <p>
                                    敬文书院 -- 管理员
                                    <small>上次登录 {{ $curuser->updated_at->toFormattedDateString() }}</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <!--<li class="user-body">
                                <div class="row">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Friends</a>
                                    </div>
                                </div>
                            </li>-->
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{{ url('admin/logout ') }}" class="btn btn-default btn-flat">退出</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

resources/views/admin/_partials/left.blade.php
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="/assets/images/user.jpg" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ $curuser->nickname }}</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                  <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                  </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header">主要导航</li>
                @inject('commonServices','App\Services\CommonServices')
                @foreach($commonServices::getMenus() as $menu)
                   @if(($menu['name'] !== '#') && !Route::has($menu['name']))
                        @continue
                    @endif
                   <li class="{{ $menu['class'] }} treeview">
                       <a href="{{ $menu['href'] }}">
                           {!! $menu['icon_html'] !!}  <span>{{ $menu['display_name'] }}</span>
                           @if(isset($menu['sub']))
                               <i class="fa fa-angle-left pull-right"></i>
                           @endif
                       </a>
                   @if(!isset($menu['sub']))
                   </li>
                       @continue
                   @endif
                       <ul class="treeview-menu">
                           @foreach($menu['sub'] as $sub)
                           <li class="{{ $sub['class'] }}"><a href="{{ $sub['href'] }}">{!! $sub['icon'] !!}  {{ $sub['display_name'] }}</a></li>
                           @endforeach
                       </ul>
                   </li>

                @endforeach
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

resources/views/admin/_partials/rbac-left-menu.blade.php
<div class="col-sm-3 col-lg-2">
    <ul class="nav nav-pills nav-stacked nav-email">
        <li class="{!! ($curRoutes[1] == 'users') ? 'active' : '' !!}">
            <a href="{{ route('admin.users.index') }}">
                <span class="badge pull-right"></span>
                <i class="fa fa-user"></i> 用户管理
            </a>
        </li>
        <li class="{!! ($curRoutes[1] == 'role') ? 'active' : '' !!}">
            <a href="{{ route('admin.role.index') }}">
                <span class="badge pull-right"></span>
                <i class="fa fa-users"></i> 角色管理
            </a>
        </li>
        <li class="{!! ($curRoutes[1] == 'permission') ? 'active' : '' !!}">
            <a href="{{ route('admin.permission.index') }}">
                <span class="badge pull-right"></span>
                <i class="fa fa-key"></i> 权限管理
            </a>
        </li>
    </ul>
</div><!-- col-sm-3 -->